// Create + publish the nudge email templates in your Resend account, then write
// the resulting ids to app/nudges/template-ids.ts. Idempotent: templates that
// already exist (by name) are reused, not recreated — so edits you make in the
// Resend UI are preserved. Re-run any time you ADD a new template def.
//   npx tsx --env-file=.env scripts/resend-templates.ts
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { TEMPLATE_DEFS, TEMPLATE_FROM } from "../app/nudges/templates";

const key = process.env.RESEND_API_KEY;
if (!key) throw new Error("RESEND_API_KEY missing (run with --env-file=.env)");
const H = { authorization: `Bearer ${key}`, "content-type": "application/json" };

async function json(res: Response): Promise<any> {
  const body = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(`${res.status} ${JSON.stringify(body)}`);
  return body;
}

// Existing templates by name → id (handles {data:[...]} or [...] shapes).
async function existing(): Promise<Map<string, string>> {
  const body = await json(await fetch("https://api.resend.com/templates", { headers: H }));
  const list: any[] = Array.isArray(body) ? body : (body.data ?? []);
  return new Map(list.map((t) => [t.name, t.id]));
}

async function main() {
  const have = await existing();
  const ids: Record<string, string> = {};

  const force = process.env.FORCE === "1"; // update existing templates in place

  for (const def of TEMPLATE_DEFS) {
    const known = have.get(def.name);
    if (known && !force) {
      ids[def.key] = known;
      console.log(`= exists   ${def.key} (${known})`);
      continue;
    }
    if (known && force) {
      await json(
        await fetch(`https://api.resend.com/templates/${known}`, {
          method: "PATCH",
          headers: H,
          body: JSON.stringify({ html: def.html, subject: def.subject, variables: def.variables }),
        }),
      );
      await json(await fetch(`https://api.resend.com/templates/${known}/publish`, { method: "POST", headers: H }));
      ids[def.key] = known;
      console.log(`~ updated  ${def.key} (${known})`);
      continue;
    }
    const created = await json(
      await fetch("https://api.resend.com/templates", {
        method: "POST",
        headers: H,
        body: JSON.stringify({
          name: def.name,
          from: TEMPLATE_FROM,
          subject: def.subject,
          html: def.html,
          variables: def.variables,
        }),
      }),
    );
    const id: string = created.id ?? created.data?.id;
    await json(await fetch(`https://api.resend.com/templates/${id}/publish`, { method: "POST", headers: H }));
    ids[def.key] = id;
    console.log(`+ created  ${def.key} (${id})`);
  }

  const out =
    `// AUTO-GENERATED by scripts/resend-templates.ts — do not edit by hand.\n` +
    `export const TEMPLATE_IDS: Record<string, string> = ${JSON.stringify(ids, null, 2)};\n`;
  const path = fileURLToPath(new URL("../app/nudges/template-ids.ts", import.meta.url));
  writeFileSync(path, out);
  console.log(`\nwrote ${Object.keys(ids).length} ids → app/nudges/template-ids.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
