// AUTO-GENERATED by scripts/resend-templates.ts — do not edit by hand.
export const TEMPLATE_IDS: Record<string, string> = {
  "onboarding-welcome": "3f7e9829-5685-490d-a344-db33696072a6",
  "onboarding-brand": "9ddd8e91-1602-4fbc-a85e-f12c26ce78ea",
  "onboarding-knowledge": "3991c4ce-dfc5-436f-8552-e05813d268ff",
  "onboarding-results": "5974a953-08c8-4154-9353-049e56d950ae",
  "usage-warn": "899ee8e9-e95e-4b88-8fd6-3ac7dd5726fc",
  "usage-exhausted": "21b58d1c-041e-45d7-9a8f-640d9b7e294b",
  "announcement": "e232c51d-f517-42e8-bcba-42ae6f3017d4"
};
